input.onButtonPressed(Button.A, function on_button_pressed_a() {
    basic.showNumber(5)
    basic.pause(1000)
    basic.showNumber(4)
    basic.pause(1000)
    pins.digitalWritePin(DigitalPin.P0, 1)
    basic.showNumber(3)
    basic.pause(1000)
    pins.digitalWritePin(DigitalPin.P1, 1)
    basic.showNumber(2)
    basic.pause(1000)
    pins.digitalWritePin(DigitalPin.P2, 1)
    basic.showNumber(1)
    basic.pause(1000)
    pins.digitalWritePin(DigitalPin.P0, 1)
    pins.digitalWritePin(DigitalPin.P1, 1)
    pins.digitalWritePin(DigitalPin.P2, 1)
    basic.showString("BLAST OFF!!")
    pins.digitalWritePin(DigitalPin.P0, 0)
    basic.pause(1000)
    pins.digitalWritePin(DigitalPin.P1, 0)
    basic.pause(1000)
    pins.digitalWritePin(DigitalPin.P2, 0)
})
