def on_button_pressed_a():
    basic.show_number(5)
    basic.pause(1000)
    basic.show_number(4)
    basic.pause(1000)
    pins.digital_write_pin(DigitalPin.P0, 1)
    basic.show_number(3)
    basic.pause(1000)
    pins.digital_write_pin(DigitalPin.P1, 1)
    basic.show_number(2)
    basic.pause(1000)
    pins.digital_write_pin(DigitalPin.P2, 1)
    basic.show_number(1)
    basic.pause(1000)
    pins.digital_write_pin(DigitalPin.P0, 1)
    pins.digital_write_pin(DigitalPin.P1, 1)
    pins.digital_write_pin(DigitalPin.P2, 1)
    basic.show_string("BLAST OFF!!")
    pins.digital_write_pin(DigitalPin.P0, 0)
    basic.pause(1000)
    pins.digital_write_pin(DigitalPin.P1, 0)
    basic.pause(1000)
    pins.digital_write_pin(DigitalPin.P2, 0)
input.on_button_pressed(Button.A, on_button_pressed_a)
